wandb_version: 1

height:
  desc: null
  value: 100
width:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 48
architecture:
  desc: null
  value: FFNN
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681168172.555771
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
