wandb_version: 1

height:
  desc: null
  value: 224
width:
  desc: null
  value: 224
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 50
architecture:
  desc: null
  value: CNN
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681766173.229305
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
